apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "live-stream-packager.fullname" . }}-nginx
  labels:
    {{- include "live-stream-packager.labels" . | nindent 4 }}
    app.kubernetes.io/component: web
data:
  default.conf: |
    map $uri $stream_cache_control {
        default                         "public, max-age=31536000, immutable";
        ~*\.(m3u8|mpd)$                "no-cache, no-store, must-revalidate";
    }

    server {
        listen       80;
        listen  [::]:80;
        server_name  _;

        location / {
            root /usr/share/nginx/html;

            add_header 'Access-Control-Allow-Origin' '*' always;
            add_header 'Access-Control-Allow-Methods' 'GET, HEAD, OPTIONS' always;
            add_header 'Access-Control-Allow-Headers' 'Range, Origin, Accept, Content-Type' always;
            add_header 'Cache-Control' $stream_cache_control always;
            add_header 'X-Content-Type-Options' 'nosniff' always;

            if ($request_method = 'OPTIONS') {
                add_header 'Access-Control-Allow-Origin' '*' always;
                add_header 'Access-Control-Allow-Methods' 'GET, HEAD, OPTIONS' always;
                add_header 'Access-Control-Allow-Headers' 'Range, Origin, Accept, Content-Type' always;
                add_header 'Access-Control-Max-Age' 86400;
                add_header 'Content-Length' 0;
                add_header 'Content-Type' 'text/plain; charset=utf-8';
                return 204;
            }

            try_files $uri =404;
        }
    }
