apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "live-stream-packager.fullname" . }}-scripts
  labels:
    {{- include "live-stream-packager.labels" . | nindent 4 }}
data:
  run-packager.sh: |
{{ .Files.Get "scripts/run-packager.sh" | indent 4 }}
  playlist-healthcheck.sh: |
{{ .Files.Get "scripts/playlist-healthcheck.sh" | indent 4 }}
  cubemap-input-healthcheck.sh: |
{{ .Files.Get "scripts/cubemap-input-healthcheck.sh" | indent 4 }}
